### PR TITLE
Code review (8.2.2020) changes

### PR DESCRIPTION
**Pull request by lmark1**
- [Rotate translation error](https://github.com/larics/cartographer/blob/7c329164a1de9e3a0d5361093f7d129ce6920950/cartographer/mapping/internal/optimization/cost_functions/landmark_cost_function_2d.h#L74)
-  optimization problem 2d - [add Huber loss option and separate Huber scale for Landmark](https://github.com/larics/cartographer/blob/7c329164a1de9e3a0d5361093f7d129ce6920950/cartographer/mapping/internal/optimization/optimization_problem_2d.cc#L148)
- optimization problem 3d - [add Huber loss option and separate Huber scale for Landmark](https://github.com/larics/cartographer/blob/7c329164a1de9e3a0d5361093f7d129ce6920950/cartographer/mapping/internal/optimization/optimization_problem_3d.cc#L196)

### CODE REVIEW

**Comment by lmark1** [comment]
@RobertMilijas  Updated parameter sets at [uav_ros_general](https://github.com/lmark1/uav_ros_general)

**Review by ojura — APPROVED** [review]

**Comment by ojura** [comment]
Shall we merge this into GPS landmarks as well?

**Comment by ojura** [comment]
BTW does weight of 0 mean "do not scale with covariance"?

I would still introduce an affine transform (weight * inv_cov + const_weight) rather than having special meaning for 0.

**Comment by lmark1** [comment]
There is a [flag ](https://github.com/larics/cartographer_ros/blob/ac57c89970033f63147616c1ff9927ed8e7c2568/cartographer_ros/cartographer_ros/sensor_bridge.cc#L128) for enabling inverse_covariance scaling .

**Comment by ojura** [comment]
Yes, but I think affine gives you most options:

weight = 0, const = 2 -> every measurement is 2
weight = 1, const = 0 -> every measurement is 1 / cov

weight = x, const = y -> every measurement is x / cov + y

I suggest this because gives greater flexibility rather than having a bool. But bool is also fine, feel free to merge if you're happy

**Pull request merged**
